import datetime
today=datetime.datetime.now()
print(today)
print(today.day,"January")
#we can't cahnge date today.day=21
yesterday=datetime.datetime.now()-datetime.timedelta(days=1)
print(yesterday)
print("Difference between 2 days:",today-yesterday)
print(today.strftime("%d/%m/%Y,%H:%M:%S"))
print(today.strftime("Today is: %A"))
print(today.strftime("The number of week in the year: %W"))
#print(today.total_seconds())
print((today-yesterday).total_seconds())
today=today.replace(day=10)
print (today)
