insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (51, 'Kalemie Airport', 'Mexico', 'Villa Hidalgo', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (52, 'San Pedro Airport', 'Spain', 'Tudela', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (53, 'Silchar Airport', 'Thailand', 'Na Kae', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (54, 'Granite Mountain Air Station', 'Malaysia', 'Klang', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (55, 'Gyumri Shirak Airport', 'Ukraine', 'Dobrotvir', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (56, 'Qianjiang Wulingshan Airport', 'Peru', 'Tarapoto', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (57, 'Futaleufú Airport', 'Brazil', 'Mara Rosa', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (58, 'Berkley Municipal Airport', 'Algeria', 'Sidi Slimane', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (59, 'Mount Isa Airport', 'Nigeria', 'Bama', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (60, 'Marrakech Menara Airport', 'Poland', 'Strzelce Opolskie', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (61, 'Faribault Municipal Airport', 'United Kingdom', 'Dunfermline', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (62, 'Holland Landing Airpark', 'Russia', 'Saratov', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (63, 'Minneapolis–Saint Paul International Airport', 'United States', 'Minneapolis', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (64, 'Dubrovnik Airport', 'Croatia', 'Dubrovnik', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (65, 'Quanzhou Jinjiang International Airport', 'China', 'Quanzhou', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (66, 'Tauranga Airport', 'New Zealand', 'Tauranga', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (67, 'Redding Municipal Airport', 'United States', 'Redding', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (68, 'Palermo Airport', 'Italy', 'Palermo', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (69, 'Male Airport', 'Maldives', 'Malé', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (70, 'Kitwe Southdowns Airport', 'Zambia', 'Kitwe', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (71, 'Ouesso Airport', 'Republic of the Congo', 'Ouesso', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (72, 'Aden Adde International Airport', 'Somalia', 'Mogadishu', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (73, 'Reykjavik Airport', 'Iceland', 'Reykjavik', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (74, 'Simferopol International Airport', 'Russia', 'Simferopol', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (75, 'Khartoum International Airport', 'Sudan', 'Khartoum', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (76, 'Saarbrücken Airport', 'Germany', 'Saarbrücken', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (77, 'Cotonou Cadjehoun Airport', 'Benin', 'Cotonou', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (78, 'Ministro Pistarini International Airport', 'Argentina', 'Buenos Aires', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (79, 'Madeira Airport', 'Portugal', 'Madeira', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (80, 'Goroka Airport', 'Papua New Guinea', 'Goroka', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (81, 'Hamburg Airport', 'Germany', 'Hamburg', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (82, 'Toulouse-Blagnac Airport', 'France', 'Toulouse', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (83, 'Quito Mariscal Sucre International Airport', 'Ecuador', 'Quito', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (84, 'Nice Côte Azur Airport', 'France', 'Nice', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (85, 'Kilimanjaro International Airport', 'Tanzania', 'Arusha', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (86, 'Don Mueang International Airport', 'Thailand', 'Bangkok', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (87, 'Sharjah International Airport', 'United Arab Emirates', 'Sharjah', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (88, 'Antalya Airport', 'Turkey', 'Antalya', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (89, 'Warsaw Chopin Airport', 'Poland', 'Warsaw', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (90, 'Helsinki-Vantaa Airport', 'Finland', 'Helsinki', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (91, 'Vancouver International Airport', 'Canada', 'Vancouver', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (92, 'Christchurch International Airport', 'New Zealand', 'Christchurch', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (93, 'Zurich Airport', 'Switzerland', 'Zurich', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (94, 'Sydney Kingsford Smith Airport', 'Australia', 'Sydney', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (95, 'Cape Town International Airport', 'South Africa', 'Cape Town', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (96, 'Lisbon Humberto Delgado Airport', 'Portugal', 'Lisbon', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (97, 'Wick Airport', 'Albania', 'Novoselë', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (98, 'Tokyo Haneda Airport', 'Japan', 'Tokyo', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (99, 'Dubai International Airport', 'United Arab Emirates', 'Dubai', NOW(), NOW());
insert into airport (airport_id, airport_name, country, city, created_at, updated_at) values (100, 'Toronto Pearson International Airport', 'Canada', 'Toronto', NOW(), NOW());
